<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
    <Configurations>Debug;Release</Configurations>
    <LangVersion>12.0</LangVersion>
    <IsPackable>false</IsPackable>
    <Nullable>disable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="SAM.Analytical">
      <HintPath>..\..\..\SAM\build\SAM.Analytical.dll</HintPath>
    </Reference>
    <Reference Include="SAM.Core">
      <HintPath>..\..\..\SAM\build\SAM.Core.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
    <PackageReference Include="xunit" Version="2.9.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" />
    <PackageReference Include="Xunit.StaFact" Version="1.2.69" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\SAM.Analytical.UI.WPF\SAM.Analytical.UI.WPF.csproj" />
  </ItemGroup>
</Project>
